//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""ChargeBar"",
            ""id"": ""fa763f30-7691-4a14-93a7-6ccf7d08cc84"",
            ""actions"": [
                {
                    ""name"": ""Charging"",
                    ""type"": ""Button"",
                    ""id"": ""06559581-1e34-4c47-ac24-47aaa4b14d11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""181c321e-cf6d-4346-b15a-7eb86c84dd73"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Charging"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ChargeBar
        m_ChargeBar = asset.FindActionMap("ChargeBar", throwIfNotFound: true);
        m_ChargeBar_Charging = m_ChargeBar.FindAction("Charging", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ChargeBar
    private readonly InputActionMap m_ChargeBar;
    private IChargeBarActions m_ChargeBarActionsCallbackInterface;
    private readonly InputAction m_ChargeBar_Charging;
    public struct ChargeBarActions
    {
        private @PlayerInputActions m_Wrapper;
        public ChargeBarActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Charging => m_Wrapper.m_ChargeBar_Charging;
        public InputActionMap Get() { return m_Wrapper.m_ChargeBar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ChargeBarActions set) { return set.Get(); }
        public void SetCallbacks(IChargeBarActions instance)
        {
            if (m_Wrapper.m_ChargeBarActionsCallbackInterface != null)
            {
                @Charging.started -= m_Wrapper.m_ChargeBarActionsCallbackInterface.OnCharging;
                @Charging.performed -= m_Wrapper.m_ChargeBarActionsCallbackInterface.OnCharging;
                @Charging.canceled -= m_Wrapper.m_ChargeBarActionsCallbackInterface.OnCharging;
            }
            m_Wrapper.m_ChargeBarActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Charging.started += instance.OnCharging;
                @Charging.performed += instance.OnCharging;
                @Charging.canceled += instance.OnCharging;
            }
        }
    }
    public ChargeBarActions @ChargeBar => new ChargeBarActions(this);
    public interface IChargeBarActions
    {
        void OnCharging(InputAction.CallbackContext context);
    }
}
